
name: maven-dev

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Maven version
      run: |
        curl \
           -X POST \
           -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/hemantbhosale916/hello-world/actions/workflows/workflows-dispatch.yaml/dispatches \
           -d '{"ref":"master"}'
