name: my branch - Manually triggered workflow 
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo " calling from my branch"
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
        
    - run: echo "::set-env name=DAY_OF_WEEK::$( date +%a )"
    - run: echo "Somebody has a case of the mondays!"
      if: env.DAY_OF_WEEK == 'Mon'
    - run: echo "This runs every day..."
    - name: new syntax
      run: echo "FOO= ${{ secrets.FIRST_NAME }}" >> $GITHUB_ENV
    - name: get value
      run: echo $FOO
    - name: hemant
      run: echo "this is hemant"
      if: env.FOO == 'hemant'
    - name: Not hemant
      run: echo "this is not  hemant"
      if: env.FOO == 'hadasemant'
