name: my branch - Manually triggered workflow 
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
    - name: echo actor
      run: echo ${{ github.actor }} 
    
    - name: echo owner
      run: echo ${{ github.repository_owner	 }}
      
    - run: |
        echo " calling from my branch"
        echo "Hello ${{ github.event.inputs.name }}!"
        echo "- in ${{ github.event.inputs.home }}!"
        
    - run: echo "::set-env name=DAY_OF_WEEK::$( date +%a )"
    - name: today is monday
      if: env.DAY_OF_WEEK == 'Mon'
      run: echo "Somebody has a case of the mondays!"
 
    - run: echo "This runs every day..."
    - name: new syntax
      run: echo "LAST_NAME=${{ secrets.FIRST_NAME }}" >> $GITHUB_ENV
    - name: get value
      run: echo env.LAST_NAME
    - name: hemant
      run: echo "this is hemant"
      if: ${{ env.LAST_NAME }} == 'hemant'
    - name: Not hemant
      run: echo "this is not  hemant"
      if: ${{ env.LAST_NAME }} == 'hadasemant'
